AUG:
  COLOR_JITTER: 0.4
DATA:
  BATCH_SIZE: 256
  DATA_PATH: "../data/"
  DATASET: "medium_imagenet"
  IMG_SIZE: 224
  NUM_WORKERS: 32
  PIN_MEMORY: True
MODEL:
  NAME: alexnet
  NUM_CLASSES: 200
  DROP_RATE: 0.0
TRAIN:
  EPOCHS: 10
  WARMUP_EPOCHS: 2
  LR: 3e-4
  MIN_LR: 3e-5
  WARMUP_LR: 3e-5
  LR_SCHEDULER:
    NAME: "cosine"
  OPTIMIZER:
    NAME: "adamw"
    EPS: 1e-8
    BETAS: (0.9, 0.999)
    MOMENTUM: 0.9
OUTPUT: "output/alexnet_med"
SAVE_FREQ: 1
PRINT_FREQ: 5000